### ISSUE TITLE
[bug] Crossbow convert not work

### ISSUE THREAD

**Issue by PanHaskins** [BrilliantTeam/Minecraft-ResourcePack-Migrator#4]
I have a vanilla crossbow in the base.

![image](https://github.com/user-attachments/assets/04d828a2-1d63-4cc9-8dd0-5189e030cab3)
![image](https://github.com/user-attachments/assets/e362c5fe-279b-4280-99d9-14b003ce3a6d)

Assets for testing
[assets.zip](https://github.com/user-attachments/files/18138144/assets.zip)

Version 1.20.4 -> 1.21.4

**Comment by RICE0707** [comment]
This converter only processes JSON files located in the ` models/item ` directory that include ` Custom Model Data ` or ` Custom Model Data + Damage. `

**Comment by RICE0707** [comment]
It is evident that your resource pack format does not meet the conversion requirements of the converter. Therefore, the converter will not process it. This is the expected behavior and not a bug. I also have no plans to support resource pack formats other than those using custom model data.

**Comment by RICE0707** [comment]
If you ensure that `crossbow.json` is located in the `model/item` directory, you will also need to configure it according to the following `overrides` format:

```json
{"predicate": {"custom_model_data": 1}, "model": "item/crossbow/1_standby"},
{"predicate": {"custom_model_data": 1, "pulling": 1}, "model": "item/crossbow/1_pulling_0"},
{"predicate": {"custom_model_data": 1, "pulling": 1, "pull": 0.58}, "model": "item/crossbow/1_pulling_1"},
{"predicate": {"custom_model_data": 1, "pulling": 1, "pull": 1.0}, "model": "item/crossbow/1_pulling_2"},
{"predicate": {"custom_model_data": 1, "charged": 1}, "model": "item/crossbow/1_arrow"},
{"predicate": {"custom_model_data": 1, "charged": 1, "firework": 1}, "model": "item/crossbow/1_firework"}
```

Only by including these will it be correctly converted into the new format.

**Comment by RICE0707** [comment]
![image](https://github.com/user-attachments/assets/1d073579-302f-493b-8f96-0eac03f4dee0)
I tested the resource pack you provided after adding the `crossbow.json` file to the `model/item` directory:  
```
{"predicate": {"custom_model_data":3}, "model": "item/crossbow/beach_crossbow"},
{"predicate": {"custom_model_data":3, "pulling": 1}, "model": "item/crossbow/beach_crossbow_0"},
{"predicate": {"custom_model_data":3, "pulling": 1, "pull": 0.58}, "model": "item/crossbow/beach_crossbow_1"},
{"predicate": {"custom_model_data":3, "pulling": 1, "pull": 1.0}, "model": "item/crossbow/beach_crossbow_2"},
{"predicate": {"custom_model_data":3, "charged": 1}, "model": "item/crossbow/beach_crossbow_charged"},
{"predicate": {"custom_model_data":3, "charged": 1, "firework": 1}, "model": "item/crossbow/beach_crossbow_firework"}
```  
Conclusion: The converter works as expected.

**Comment by PanHaskins** [comment]
[crossbow.json](https://github.com/user-attachments/files/18140721/crossbow.json)
I had this crossbow.json in minecraft:models/item in resourcepack

**Comment by RICE0707** [comment]
You need to manually delete the abnormal JSON sections after the conversion, specifically:  
```json
{
    "threshold": 50001,
    "model": {
        "type": "minecraft:condition",
        "property": "minecraft:using_item",
        "on_false": {
            "type": "minecraft:select",
            "property": "minecraft:charge_type",
            "fallback": {
                "type": "minecraft:model",
                "model": "item/crossbow"
            },
            "cases": []
        },
        "on_true": {
            "type": "minecraft:range_dispatch",
            "property": "minecraft:crossbow/pull",
            "fallback": {
                "type": "minecraft:model",
                "model": "item/crossbow"
            },
            "entries": []
        }
    }
}
```  
This is because, in the original JSON file:  
```json
{
    "predicate": {
        "custom_model_data": 50001
    },
    "model": "item/crossbow"
}
```  
a `custom_model_data` parameter is present but lacks definitions for other required crossbow parameters, such as `pulling`, `pull`, and `firework`.  

This results in an incomplete JSON after the conversion, leading to display issues.  

In summary, this is not an error with the converter but rather a result of missing definitions in the original resource pack.

**Comment by SuperKael** [comment]
The other definitions are actually not required, so the converter outputting incomplete JSON without them is indeed an error with the converter. I would greatly appreciate it if you would fix this.
