### ISSUE TITLE
[bug] bowl conversion

### ISSUE THREAD

**Issue by JasmineWMCM** [BrilliantTeam/Minecraft-ResourcePack-Migrator#6]
**Describe the bug**

**To Reproduce**
1. Go to 'convert the pack'
2. Click on 'start convert'
3. Scroll down to 'the pack output and click on "Bowl"'

**Expected behavior**
It keeps on think that the bowl.json is BOW.json and keeps on generating bows.

**Screenshots**
https://jasmine.pics/1il0fzxh.png

**Desktop (please complete the following information):**
 - OS: win. 11
 - Browser Firefox
 - Version 133.0.3 (64-bit)

**Additional context**

**Comment by RICE0707** [comment]
Oh, that’s such a silly mistake! I’ll fix it in the next version. Thanks for your feedback and for using the converter!

**Comment by RICE0707** [comment]
This judgment error was fixed in version 1.3.4.
