### ISSUE TITLE
[enhancement] saving data

### ISSUE THREAD

**Issue by JasmineWMCM** [BrilliantTeam/Minecraft-ResourcePack-Migrator#7]
**Is your feature request related to a problem? Please describe.**
I am Taiwanese and I can read Chinese fine but I was born in the United States and I prefer English and I wish the output folder would save to my latest since I don't want the conversions in the C: folder but in my D: folder where I have far more space.

**Describe the solution you'd like**
If I boot up the program I am able to save my language selection and my output folder.

**Describe alternatives you've considered**
An alternative to language could be two different files but I think my solution above should be pretty clean.

**Additional context**
Nope! Thank you, I also boot in administrative mode.

**Comment by RICE0707** [comment]
In the next version, I’ll implement this idea.  
The program will create a new `settings.json` file in its folder,  
currently used to store language and output folder settings:  
```json
{
    "language": "en",
    "output_dir": "C:\\Program Files\\MCPackConverter\\output"
}
```

**Comment by RICE0707** [comment]
Version 1.3.5 has been released, adding persistent data storage for language and output folder settings.
